###H2 Datenbank wegen Startschwieriegkeiten, spaeter Migration
###Auf PostgreSQL
5,4 +5,5 @@ spring:
  path: /h2-console  jpa:    properties:      javax:
                             persistence:
                               validation:
                                 mode: none  data:    web:      pageable:        default-page-size: 10
                             max-page-size: 100



#
#spring.datasource.url = jdbc:postgresql://localhost:5432/projekt
##DataSourceSettings#
#
#
##Username und Secret
#spring.datasource.username =
#spring.datasource.password =
#
##Keep the connection alive if idle for a long time
#spring.datasource.tomcat.test-while-idle=true
#spring.datasource.tomcat.validation-query= SELECT 1
#

