###H2 Datenbank wegen Startschwieriegkeiten, spaeter Migration
###Auf PostgreSQL
---
spring:
  profiles: prod
  datasource:    url: jdbc:h2:./textify-prod
  jpa:    hibernate:      ddl-auto: update
  h2:
    console:      enabled: false
hoaxify:
  upload-path: uploads-prod
---
spring:
  profiles: dev
  datasource:    url: jdbc:h2:mem:textify-dev
hoaxify:
  upload-path: uploads-dev
---
spring:
  profiles: test
hoaxify:
  upload-path: uploads-test


#
#spring.datasource.url = jdbc:postgresql://localhost:5432/projekt
##DataSourceSettings#
#
#
##Username und Secret
#spring.datasource.username =
#spring.datasource.password =
#
##Keep the connection alive if idle for a long time
#spring.datasource.tomcat.test-while-idle=true
#spring.datasource.tomcat.validation-query= SELECT 1
#

